### ISSUE TITLE
Cannot "Sign in with Google"

### ISSUE THREAD

**Issue by mileszs** [unixmonkey/convoter#11]
I'm not sure what is happening. Chrome 78.0.3904.87.

1. Click "Sign in with Google"
2. Get prompted to choose my account
3. Get redirected to convoter
4. Not actually signed in :-/

I'll try with other browsers and such later.

**Comment by unixmonkey** [comment]
I'm seeing that with my account, too. 
There's something I need to do to fix the OAuth integration:

> "Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>403, "message"=>"Legacy People API has not been used in project 493142023343 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=493142023343 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "status"=>"PERMISSION_DENIED", "details"=>[{"@type"=>"type.googleapis.com/google.rpc.Help", "links"=>[{"description"=>"Google developers console API activation", "url"=>"https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=493142023343"}]}]}:

However, when I visit that URL, it says "There was an error while loading".

I think this may have to do with it being a Google+ API, and it having shut down in March of this year:
https://developers.google.com/+/api-shutdown

Under my account it shows that I'm using the Google+ API.

I'll try to take a closer look over lunch or tonight.

**Comment by unixmonkey** [comment]
Turns out a simple `bundle update devise omniauth omniauth-google-oauth2` was enough to get it going again. Closing this, but feel free to reopen if you are still having trouble.

**Comment by mileszs** [comment]
@unixmonkey Awesome! Thanks for figuring that out before I could even get around to digging into it. I know some folks going to their first conference that will get a lot of use out of convoter.

**Comment by Piyush-Chaudhary** [comment]
I was also having the same issue with my Rails app. So I resolved it by upgrading the omniauth gems by running` bundle update devise omniauth omniauth-google-oauth2` in the terminal.
